/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from '../a2t-shared/a2t-headline/a2t-headline.component.ngfactory';
import * as i2 from '../a2t-shared/a2t-headline/a2t-headline.component';
import * as i3 from '../a2t-shared/a2t-error/a2t-error.component.ngfactory';
import * as i4 from '../a2t-shared/a2t-error/a2t-error.component';
import * as i5 from '../a2t-shared/a2t-form/a2t-form.component.ngfactory';
import * as i6 from '../a2t-shared/a2t-form/a2t-form.component';
import * as i7 from '../a2t-shared/a2t-form/a2t-form.service';
import * as i8 from '../a2t-shared/a2t-links/a2t-links.component.ngfactory';
import * as i9 from '../a2t-shared/a2t-links/a2t-links.component';
import * as i10 from './a2t-sign-up.component';
import * as i11 from '../../angular2-token.service';
import * as i12 from '@angular/router';
const styles_A2tSignUpComponent:any[] = ([] as any[]);
export const RenderType_A2tSignUpComponent:i0.RendererType2 = i0.ɵcrt({encapsulation:2,
    styles:styles_A2tSignUpComponent,data:{}});
export function View_A2tSignUpComponent_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵted((null as any),['\n        '])),(_l()(),i0.ɵeld(0,
      (null as any),(null as any),2,'a2t-headline',([] as any[]),(null as any),(null as any),
      (null as any),i1.View_A2tHeadlineComponent_0,i1.RenderType_A2tHeadlineComponent)),
      i0.ɵdid(49152,(null as any),0,i2.A2tHeadlineComponent,([] as any[]),(null as any),
          (null as any)),(_l()(),i0.ɵted(0,['Sign Up'])),(_l()(),i0.ɵted((null as any),
          ['\n        '])),(_l()(),i0.ɵeld(0,(null as any),(null as any),1,'a2t-error',
          ([] as any[]),(null as any),(null as any),(null as any),i3.View_A2tErrorComponent_0,
          i3.RenderType_A2tErrorComponent)),i0.ɵdid(49152,(null as any),0,i4.A2tErrorComponent,
          ([] as any[]),{errors:[0,'errors']},(null as any)),(_l()(),i0.ɵted((null as any),
          ['\n        '])),(_l()(),i0.ɵeld(0,(null as any),(null as any),2,'a2t-form',
          ([] as any[]),(null as any),(null as any),(null as any),i5.View_A2tFormComponent_0,
          i5.RenderType_A2tFormComponent)),i0.ɵdid(49152,(null as any),0,i6.A2tFormComponent,
          [i7.A2tFormService],(null as any),(null as any)),(_l()(),i0.ɵted(0,['Sign Up'])),
      (_l()(),i0.ɵted((null as any),['\n        '])),(_l()(),i0.ɵeld(0,(null as any),
          (null as any),1,'a2t-links',[['case','sign-up']],(null as any),(null as any),
          (null as any),i8.View_A2tLinksComponent_0,i8.RenderType_A2tLinksComponent)),
      i0.ɵdid(49152,(null as any),0,i9.A2tLinksComponent,([] as any[]),{case:[0,'case']},
          (null as any)),(_l()(),i0.ɵted((null as any),['\n    ']))],(_ck,_v) => {
    var _co:i10.A2tSignUpComponent = _v.component;
    const currVal_0:any = _co._errors;
    _ck(_v,6,0,currVal_0);
    const currVal_1:any = 'sign-up';
    _ck(_v,13,0,currVal_1);
  },(null as any));
}
export function View_A2tSignUpComponent_Host_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,(null as any),(null as any),2,'a2t-sign-up',
      ([] as any[]),(null as any),(null as any),(null as any),View_A2tSignUpComponent_0,
      RenderType_A2tSignUpComponent)),i0.ɵprd(512,(null as any),i7.A2tFormService,
      i7.A2tFormService,([] as any[])),i0.ɵdid(49152,(null as any),0,i10.A2tSignUpComponent,
      [i7.A2tFormService,i11.Angular2TokenService,i12.Router],(null as any),(null as any))],
      (null as any),(null as any));
}
export const A2tSignUpComponentNgFactory:i0.ComponentFactory<i10.A2tSignUpComponent> = i0.ɵccf('a2t-sign-up',
    i10.A2tSignUpComponent,View_A2tSignUpComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL2hvbWUvamFzb24vYW5ndWxhcjItdG9rZW4vc3JjL2EydC11aS9hMnQtc2lnbi11cC9hMnQtc2lnbi11cC5jb21wb25lbnQubmdmYWN0b3J5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vaG9tZS9qYXNvbi9hbmd1bGFyMi10b2tlbi9zcmMvYTJ0LXVpL2EydC1zaWduLXVwL2EydC1zaWduLXVwLmNvbXBvbmVudC50cyIsIm5nOi8vL2hvbWUvamFzb24vYW5ndWxhcjItdG9rZW4vc3JjL2EydC11aS9hMnQtc2lnbi11cC9hMnQtc2lnbi11cC5jb21wb25lbnQudHMuQTJ0U2lnblVwQ29tcG9uZW50Lmh0bWwiLCJuZzovLy9ob21lL2phc29uL2FuZ3VsYXIyLXRva2VuL3NyYy9hMnQtdWkvYTJ0LXNpZ24tdXAvYTJ0LXNpZ24tdXAuY29tcG9uZW50LnRzLkEydFNpZ25VcENvbXBvbmVudF9Ib3N0Lmh0bWwiXSwic291cmNlc0NvbnRlbnQiOlsiICIsIlxuICAgICAgICA8YTJ0LWhlYWRsaW5lPlNpZ24gVXA8L2EydC1oZWFkbGluZT5cbiAgICAgICAgPGEydC1lcnJvciBbZXJyb3JzXT1cIl9lcnJvcnNcIj48L2EydC1lcnJvcj5cbiAgICAgICAgPGEydC1mb3JtPlNpZ24gVXA8L2EydC1mb3JtPlxuICAgICAgICA8YTJ0LWxpbmtzIGNhc2U9XCJzaWduLXVwXCI+PC9hMnQtbGlua3M+XG4gICAgIiwiPGEydC1zaWduLXVwPjwvYTJ0LXNpZ24tdXA+Il0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OztvQkNBQSwrQ0FDUTtNQUFBO01BQUE7YUFBQTtVQUFBLGVBQWMsZ0NBQXNCO1VBQUEsaUJBQ3BDO1VBQUE7eUNBQUEsVUFBQTtVQUFBLG1EQUEwQztVQUFBLGlCQUMxQztVQUFBO3dDQUFBLFVBQUE7VUFBQSxpREFBVTtNQUFrQiwrQ0FDNUI7VUFBQTtVQUFBO2FBQUE7VUFBQSxlQUFzQzs7SUFGM0I7SUFBWCxXQUFXLFNBQVg7SUFFVztJQUFYLFlBQVcsU0FBWDs7OztvQkNKUjtNQUFBO21DQUFBO3dCQUFBLHNCQUFBO01BQUE7Ozs7In0=
