/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from './a2t-ui.module';
import * as i2 from './a2t-ui.component.ngfactory';
import * as i3 from './a2t-sign-in/a2t-sign-in.component.ngfactory';
import * as i4 from './a2t-sign-up/a2t-sign-up.component.ngfactory';
import * as i5 from './a2t-reset-password/a2t-reset-password.component.ngfactory';
import * as i6 from './a2t-update-password/a2t-update-password.component.ngfactory';
import * as i7 from '@angular/common';
import * as i8 from '@angular/forms';
import * as i9 from '@angular/router';
import * as i10 from './a2t-shared/a2t-shared.module';
import * as i11 from './a2t-ui.component';
import * as i12 from './a2t-sign-in/a2t-sign-in.component';
import * as i13 from './a2t-sign-up/a2t-sign-up.component';
import * as i14 from './a2t-reset-password/a2t-reset-password.component';
import * as i15 from './a2t-update-password/a2t-update-password.component';
import * as i16 from '../angular2-token.service';
export const A2tUiModuleNgFactory:i0.NgModuleFactory<i1.A2tUiModule> = i0.ɵcmf(i1.A2tUiModule,
    ([] as any[]),(_l:any) => {
      return i0.ɵmod([i0.ɵmpd(512,i0.ComponentFactoryResolver,i0.ɵCodegenComponentFactoryResolver,
          [[8,[i2.A2tUiComponentNgFactory,i3.A2tSignInComponentNgFactory,i4.A2tSignUpComponentNgFactory,
              i5.A2tResetPasswordComponentNgFactory,i6.A2tUpdatePasswordComponentNgFactory]],
              [3,i0.ComponentFactoryResolver],i0.NgModuleRef]),i0.ɵmpd(4608,i7.NgLocalization,
          i7.NgLocaleLocalization,[i0.LOCALE_ID]),i0.ɵmpd(4608,i8.FormBuilder,i8.FormBuilder,
          ([] as any[])),i0.ɵmpd(4608,i8.ɵi,i8.ɵi,([] as any[])),i0.ɵmpd(512,i7.CommonModule,
          i7.CommonModule,([] as any[])),i0.ɵmpd(512,i9.RouterModule,i9.RouterModule,
          [[2,i9.ɵa],[2,i9.Router]]),i0.ɵmpd(512,i8.ɵba,i8.ɵba,([] as any[])),i0.ɵmpd(512,
          i8.ReactiveFormsModule,i8.ReactiveFormsModule,([] as any[])),i0.ɵmpd(512,
          i10.A2tSharedModule,i10.A2tSharedModule,([] as any[])),i0.ɵmpd(512,i1.A2tUiModule,
          i1.A2tUiModule,([] as any[])),i0.ɵmpd(1024,i9.ROUTES,() => {
        return [[{path:'session',component:i11.A2tUiComponent,children:[{path:'sign-in',
            component:i12.A2tSignInComponent},{path:'sign-up',component:i13.A2tSignUpComponent},
            {path:'reset-password',component:i14.A2tResetPasswordComponent},{path:'update-password',
                component:i15.A2tUpdatePasswordComponent,canActivate:[i16.Angular2TokenService]}]}]];
      },([] as any[]))]);
    });
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL2hvbWUvY29yd2luL3Byb2plY3RzL2FuZ3VsYXIyLXRva2VuL3NyYy9hMnQtdWkvYTJ0LXVpLm1vZHVsZS5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9ob21lL2Nvcndpbi9wcm9qZWN0cy9hbmd1bGFyMi10b2tlbi9zcmMvYTJ0LXVpL2EydC11aS5tb2R1bGUudHMiXSwic291cmNlc0NvbnRlbnQiOlsiICJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7In0=
