/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from '@angular/router';
import * as i2 from './a2t-ui.component';
const styles_A2tUiComponent:any[] = ['.a2t-wrapper[_ngcontent-%COMP%] {\n            width: 100%;\n            height: 100vh;\n            min-height: 500px;\n\n            padding-top: 100px;\n\n            display: flex;\n            justify-content: center;\n\n            background-color: #3270a0;\n        }\n\n        .a2t-logo[_ngcontent-%COMP%] {\n            text-align: center;\n            color: white;\n            font-size: 30px;\n        }\n\n        .a2t-container[_ngcontent-%COMP%] {\n            width: 400px;\n        }'];
export const RenderType_A2tUiComponent:i0.RendererType2 = i0.ɵcrt({encapsulation:0,
    styles:styles_A2tUiComponent,data:{}});
export function View_A2tUiComponent_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵted((null as any),['\n        '])),(_l()(),i0.ɵeld(0,
      (null as any),(null as any),7,'div',[['class','a2t-wrapper']],(null as any),
      (null as any),(null as any),(null as any),(null as any))),(_l()(),i0.ɵted((null as any),
      ['\n            '])),(_l()(),i0.ɵeld(0,(null as any),(null as any),4,'div',[['class',
      'a2t-container']],(null as any),(null as any),(null as any),(null as any),(null as any))),
      (_l()(),i0.ɵted((null as any),['\n                '])),(_l()(),i0.ɵeld(16777216,
          (null as any),(null as any),1,'router-outlet',([] as any[]),(null as any),
          (null as any),(null as any),(null as any),(null as any))),i0.ɵdid(212992,
          (null as any),0,i1.RouterOutlet,[i1.ChildrenOutletContexts,i0.ViewContainerRef,
              i0.ComponentFactoryResolver,[8,(null as any)],i0.ChangeDetectorRef],
          (null as any),(null as any)),(_l()(),i0.ɵted((null as any),['\n            '])),
      (_l()(),i0.ɵted((null as any),['\n        '])),(_l()(),i0.ɵted((null as any),
          ['\n    ']))],(_ck,_v) => {
    _ck(_v,6,0);
  },(null as any));
}
export function View_A2tUiComponent_Host_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,(null as any),(null as any),1,'a2t-ui',([] as any[]),
      (null as any),(null as any),(null as any),View_A2tUiComponent_0,RenderType_A2tUiComponent)),
      i0.ɵdid(49152,(null as any),0,i2.A2tUiComponent,([] as any[]),(null as any),
          (null as any))],(null as any),(null as any));
}
export const A2tUiComponentNgFactory:i0.ComponentFactory<i2.A2tUiComponent> = i0.ɵccf('a2t-ui',
    i2.A2tUiComponent,View_A2tUiComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL2hvbWUvamFzb24vYW5ndWxhcjItdG9rZW4vc3JjL2EydC11aS9hMnQtdWkuY29tcG9uZW50Lm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL2hvbWUvamFzb24vYW5ndWxhcjItdG9rZW4vc3JjL2EydC11aS9hMnQtdWkuY29tcG9uZW50LnRzIiwibmc6Ly8vaG9tZS9qYXNvbi9hbmd1bGFyMi10b2tlbi9zcmMvYTJ0LXVpL2EydC11aS5jb21wb25lbnQudHMuQTJ0VWlDb21wb25lbnQuaHRtbCIsIm5nOi8vL2hvbWUvamFzb24vYW5ndWxhcjItdG9rZW4vc3JjL2EydC11aS9hMnQtdWkuY29tcG9uZW50LnRzLkEydFVpQ29tcG9uZW50X0hvc3QuaHRtbCJdLCJzb3VyY2VzQ29udGVudCI6WyIgIiwiXG4gICAgICAgIDxkaXYgY2xhc3M9XCJhMnQtd3JhcHBlclwiPlxuICAgICAgICAgICAgPGRpdiBjbGFzcz1cImEydC1jb250YWluZXJcIj5cbiAgICAgICAgICAgICAgICA8cm91dGVyLW91dGxldD48L3JvdXRlci1vdXRsZXQ+XG4gICAgICAgICAgICA8L2Rpdj5cbiAgICAgICAgPC9kaXY+XG4gICAgIiwiPGEydC11aT48L2EydC11aT4iXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7Ozs7b0JDQUEsK0NBQ1E7TUFBQTtNQUFBLDBEQUF5QjtNQUFBLHFCQUNyQjtNQUFBO01BQTJCLHVEQUN2QjtVQUFBO1VBQUEsaUVBQUE7VUFBQTswQ0FBQTtVQUFBLDZCQUErQjtNQUM3QiwrQ0FDSjtVQUFBO0lBRkU7Ozs7b0JDSGhCO01BQUE7YUFBQTtVQUFBOzs7In0=
