/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from '@angular/router';
import * as i2 from './a2t-ui.component';
const styles_A2tUiComponent:any[] = ['.a2t-wrapper[_ngcontent-%COMP%] {\n            width: 100%;\n            height: 100vh;\n            min-height: 500px;\n\n            padding-top: 100px;\n\n            display: flex;\n            justify-content: center;\n\n            background-color: #3270a0;\n        }\n\n        .a2t-logo[_ngcontent-%COMP%] {\n            text-align: center;\n            color: white;\n            font-size: 30px;\n        }\n\n        .a2t-container[_ngcontent-%COMP%] {\n            width: 400px;\n        }'];
export const RenderType_A2tUiComponent:i0.RendererType2 = i0.ɵcrt({encapsulation:0,
    styles:styles_A2tUiComponent,data:{}});
export function View_A2tUiComponent_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵted((null as any),['\n        '])),(_l()(),i0.ɵeld(0,
      (null as any),(null as any),7,'div',[['class','a2t-wrapper']],(null as any),
      (null as any),(null as any),(null as any),(null as any))),(_l()(),i0.ɵted((null as any),
      ['\n            '])),(_l()(),i0.ɵeld(0,(null as any),(null as any),4,'div',[['class',
      'a2t-container']],(null as any),(null as any),(null as any),(null as any),(null as any))),
      (_l()(),i0.ɵted((null as any),['\n                '])),(_l()(),i0.ɵeld(16777216,
          (null as any),(null as any),1,'router-outlet',([] as any[]),(null as any),
          (null as any),(null as any),(null as any),(null as any))),i0.ɵdid(212992,
          (null as any),0,i1.RouterOutlet,[i1.ChildrenOutletContexts,i0.ViewContainerRef,
              i0.ComponentFactoryResolver,[8,(null as any)],i0.ChangeDetectorRef],
          (null as any),(null as any)),(_l()(),i0.ɵted((null as any),['\n            '])),
      (_l()(),i0.ɵted((null as any),['\n        '])),(_l()(),i0.ɵted((null as any),
          ['\n    ']))],(_ck,_v) => {
    _ck(_v,6,0);
  },(null as any));
}
export function View_A2tUiComponent_Host_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,(null as any),(null as any),1,'a2t-ui',([] as any[]),
      (null as any),(null as any),(null as any),View_A2tUiComponent_0,RenderType_A2tUiComponent)),
      i0.ɵdid(49152,(null as any),0,i2.A2tUiComponent,([] as any[]),(null as any),
          (null as any))],(null as any),(null as any));
}
export const A2tUiComponentNgFactory:i0.ComponentFactory<i2.A2tUiComponent> = i0.ɵccf('a2t-ui',
    i2.A2tUiComponent,View_A2tUiComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL2hvbWUvY29yd2luL3Byb2plY3RzL2FuZ3VsYXIyLXRva2VuL3NyYy9hMnQtdWkvYTJ0LXVpLmNvbXBvbmVudC5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9ob21lL2Nvcndpbi9wcm9qZWN0cy9hbmd1bGFyMi10b2tlbi9zcmMvYTJ0LXVpL2EydC11aS5jb21wb25lbnQudHMiLCJuZzovLy9ob21lL2Nvcndpbi9wcm9qZWN0cy9hbmd1bGFyMi10b2tlbi9zcmMvYTJ0LXVpL2EydC11aS5jb21wb25lbnQudHMuQTJ0VWlDb21wb25lbnQuaHRtbCIsIm5nOi8vL2hvbWUvY29yd2luL3Byb2plY3RzL2FuZ3VsYXIyLXRva2VuL3NyYy9hMnQtdWkvYTJ0LXVpLmNvbXBvbmVudC50cy5BMnRVaUNvbXBvbmVudF9Ib3N0Lmh0bWwiXSwic291cmNlc0NvbnRlbnQiOlsiICIsIlxuICAgICAgICA8ZGl2IGNsYXNzPVwiYTJ0LXdyYXBwZXJcIj5cbiAgICAgICAgICAgIDxkaXYgY2xhc3M9XCJhMnQtY29udGFpbmVyXCI+XG4gICAgICAgICAgICAgICAgPHJvdXRlci1vdXRsZXQ+PC9yb3V0ZXItb3V0bGV0PlxuICAgICAgICAgICAgPC9kaXY+XG4gICAgICAgIDwvZGl2PlxuICAgICIsIjxhMnQtdWk+PC9hMnQtdWk+Il0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7O29CQ0FBLCtDQUNRO01BQUE7TUFBQSwwREFBeUI7TUFBQSxxQkFDckI7TUFBQTtNQUEyQix1REFDdkI7VUFBQTtVQUFBLGlFQUFBO1VBQUE7MENBQUE7VUFBQSw2QkFBK0I7TUFDN0IsK0NBQ0o7VUFBQTtJQUZFOzs7O29CQ0hoQjtNQUFBO2FBQUE7VUFBQTs7OyJ9
