/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from '../a2t-shared/a2t-headline/a2t-headline.component.ngfactory';
import * as i2 from '../a2t-shared/a2t-headline/a2t-headline.component';
import * as i3 from '../a2t-shared/a2t-form/a2t-form.component.ngfactory';
import * as i4 from '../a2t-shared/a2t-form/a2t-form.component';
import * as i5 from '../a2t-shared/a2t-form/a2t-form.service';
import * as i6 from '../a2t-shared/a2t-links/a2t-links.component.ngfactory';
import * as i7 from '../a2t-shared/a2t-links/a2t-links.component';
import * as i8 from '@angular/common';
import * as i9 from './a2t-reset-password.component';
import * as i10 from '../../angular2-token.service';
const styles_A2tResetPasswordComponent:any[] = ['.email-send-text[_ngcontent-%COMP%] {\n            background-color: #72c380;\n            color: white;\n            font-size: 16pt;\n            text-align: center;\n            padding: 20px;\n            border-radius: 3px;\n        }'];
export const RenderType_A2tResetPasswordComponent:i0.RendererType2 = i0.ɵcrt({encapsulation:0,
    styles:styles_A2tResetPasswordComponent,data:{}});
function View_A2tResetPasswordComponent_1(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,(null as any),(null as any),2,'a2t-headline',
      ([] as any[]),(null as any),(null as any),(null as any),i1.View_A2tHeadlineComponent_0,
      i1.RenderType_A2tHeadlineComponent)),i0.ɵdid(49152,(null as any),0,i2.A2tHeadlineComponent,
      ([] as any[]),(null as any),(null as any)),(_l()(),i0.ɵted(0,['Reset your Password']))],
      (null as any),(null as any));
}
function View_A2tResetPasswordComponent_2(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,(null as any),(null as any),2,'a2t-form',([] as any[]),
      (null as any),(null as any),(null as any),i3.View_A2tFormComponent_0,i3.RenderType_A2tFormComponent)),
      i0.ɵdid(49152,(null as any),0,i4.A2tFormComponent,[i5.A2tFormService],(null as any),
          (null as any)),(_l()(),i0.ɵted(0,['Reset Password']))],(null as any),(null as any));
}
function View_A2tResetPasswordComponent_3(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,(null as any),(null as any),1,'p',[['class',
      'email-send-text']],(null as any),(null as any),(null as any),(null as any),
      (null as any))),(_l()(),i0.ɵted((null as any),['\n            If the entered email is registered we will send instruction on how to reset your password.\n        ']))],
      (null as any),(null as any));
}
function View_A2tResetPasswordComponent_4(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,(null as any),(null as any),1,'a2t-links',[['case',
      'reset-password']],(null as any),(null as any),(null as any),i6.View_A2tLinksComponent_0,
      i6.RenderType_A2tLinksComponent)),i0.ɵdid(49152,(null as any),0,i7.A2tLinksComponent,
      ([] as any[]),{case:[0,'case']},(null as any))],(_ck,_v) => {
    const currVal_0:any = 'reset-password';
    _ck(_v,1,0,currVal_0);
  },(null as any));
}
export function View_A2tResetPasswordComponent_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵted((null as any),['\n        '])),(_l()(),i0.ɵand(16777216,
      (null as any),(null as any),1,(null as any),View_A2tResetPasswordComponent_1)),
      i0.ɵdid(16384,(null as any),0,i8.NgIf,[i0.ViewContainerRef,i0.TemplateRef],{ngIf:[0,
          'ngIf']},(null as any)),(_l()(),i0.ɵted((null as any),['\n        '])),(_l()(),
          i0.ɵand(16777216,(null as any),(null as any),1,(null as any),View_A2tResetPasswordComponent_2)),
      i0.ɵdid(16384,(null as any),0,i8.NgIf,[i0.ViewContainerRef,i0.TemplateRef],{ngIf:[0,
          'ngIf']},(null as any)),(_l()(),i0.ɵted((null as any),['\n        '])),(_l()(),
          i0.ɵand(16777216,(null as any),(null as any),1,(null as any),View_A2tResetPasswordComponent_3)),
      i0.ɵdid(16384,(null as any),0,i8.NgIf,[i0.ViewContainerRef,i0.TemplateRef],{ngIf:[0,
          'ngIf']},(null as any)),(_l()(),i0.ɵted((null as any),['\n        '])),(_l()(),
          i0.ɵand(16777216,(null as any),(null as any),1,(null as any),View_A2tResetPasswordComponent_4)),
      i0.ɵdid(16384,(null as any),0,i8.NgIf,[i0.ViewContainerRef,i0.TemplateRef],{ngIf:[0,
          'ngIf']},(null as any)),(_l()(),i0.ɵted((null as any),['\n    ']))],(_ck,
      _v) => {
    var _co:i9.A2tResetPasswordComponent = _v.component;
    const currVal_0:boolean = !_co._emailSend;
    _ck(_v,2,0,currVal_0);
    const currVal_1:boolean = !_co._emailSend;
    _ck(_v,5,0,currVal_1);
    const currVal_2:any = _co._emailSend;
    _ck(_v,8,0,currVal_2);
    const currVal_3:boolean = !_co._emailSend;
    _ck(_v,11,0,currVal_3);
  },(null as any));
}
export function View_A2tResetPasswordComponent_Host_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,(null as any),(null as any),2,'a2t-reset-password',
      ([] as any[]),(null as any),(null as any),(null as any),View_A2tResetPasswordComponent_0,
      RenderType_A2tResetPasswordComponent)),i0.ɵprd(512,(null as any),i5.A2tFormService,
      i5.A2tFormService,([] as any[])),i0.ɵdid(49152,(null as any),0,i9.A2tResetPasswordComponent,
      [i5.A2tFormService,i10.Angular2TokenService],(null as any),(null as any))],(null as any),
      (null as any));
}
export const A2tResetPasswordComponentNgFactory:i0.ComponentFactory<i9.A2tResetPasswordComponent> = i0.ɵccf('a2t-reset-password',
    i9.A2tResetPasswordComponent,View_A2tResetPasswordComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL2hvbWUvamFzb24vYW5ndWxhcjItdG9rZW4vc3JjL2EydC11aS9hMnQtcmVzZXQtcGFzc3dvcmQvYTJ0LXJlc2V0LXBhc3N3b3JkLmNvbXBvbmVudC5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9ob21lL2phc29uL2FuZ3VsYXIyLXRva2VuL3NyYy9hMnQtdWkvYTJ0LXJlc2V0LXBhc3N3b3JkL2EydC1yZXNldC1wYXNzd29yZC5jb21wb25lbnQudHMiLCJuZzovLy9ob21lL2phc29uL2FuZ3VsYXIyLXRva2VuL3NyYy9hMnQtdWkvYTJ0LXJlc2V0LXBhc3N3b3JkL2EydC1yZXNldC1wYXNzd29yZC5jb21wb25lbnQudHMuQTJ0UmVzZXRQYXNzd29yZENvbXBvbmVudC5odG1sIiwibmc6Ly8vaG9tZS9qYXNvbi9hbmd1bGFyMi10b2tlbi9zcmMvYTJ0LXVpL2EydC1yZXNldC1wYXNzd29yZC9hMnQtcmVzZXQtcGFzc3dvcmQuY29tcG9uZW50LnRzLkEydFJlc2V0UGFzc3dvcmRDb21wb25lbnRfSG9zdC5odG1sIl0sInNvdXJjZXNDb250ZW50IjpbIiAiLCJcbiAgICAgICAgPGEydC1oZWFkbGluZSAqbmdJZj1cIiFfZW1haWxTZW5kXCI+UmVzZXQgeW91ciBQYXNzd29yZDwvYTJ0LWhlYWRsaW5lPlxuICAgICAgICA8YTJ0LWZvcm0gKm5nSWY9XCIhX2VtYWlsU2VuZFwiPlJlc2V0IFBhc3N3b3JkPC9hMnQtZm9ybT5cbiAgICAgICAgPHAgY2xhc3M9XCJlbWFpbC1zZW5kLXRleHRcIiAqbmdJZj1cIl9lbWFpbFNlbmRcIj5cbiAgICAgICAgICAgIElmIHRoZSBlbnRlcmVkIGVtYWlsIGlzIHJlZ2lzdGVyZWQgd2Ugd2lsbCBzZW5kIGluc3RydWN0aW9uIG9uIGhvdyB0byByZXNldCB5b3VyIHBhc3N3b3JkLlxuICAgICAgICA8L3A+XG4gICAgICAgIDxhMnQtbGlua3MgKm5nSWY9XCIhX2VtYWlsU2VuZFwiIGNhc2U9XCJyZXNldC1wYXNzd29yZFwiPjwvYTJ0LWxpbmtzPlxuICAgICIsIjxhMnQtcmVzZXQtcGFzc3dvcmQ+PC9hMnQtcmVzZXQtcGFzc3dvcmQ+Il0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7b0JDQ1E7TUFBQTt3Q0FBQSxVQUFBO01BQUEsMkNBQWtDOzs7O29CQUNsQztNQUFBO2FBQUE7VUFBQSxlQUE4Qjs7O29CQUM5QjtNQUFBO01BQUEsZ0JBQThDOzs7O29CQUc5QztNQUFBO3FDQUFBLFVBQUE7TUFBQTtJQUErQjtJQUEvQixXQUErQixTQUEvQjs7OztvQkFOUiwrQ0FDUTtNQUFBO2FBQUE7VUFBQSx3QkFBb0UsK0NBQ3BFO2lCQUFBO2FBQUE7VUFBQSx3QkFBdUQsK0NBQ3ZEO2lCQUFBO2FBQUE7VUFBQSx3QkFFSSwrQ0FDSjtpQkFBQTthQUFBO1VBQUEsd0JBQWlFOzs7SUFMbkQ7SUFBZCxXQUFjLFNBQWQ7SUFDVTtJQUFWLFdBQVUsU0FBVjtJQUMyQjtJQUEzQixXQUEyQixTQUEzQjtJQUdXO0lBQVgsWUFBVyxTQUFYOzs7O29CQ05SO01BQUE7MENBQUE7d0JBQUEsc0JBQUE7TUFBQTs7OzsifQ==
