/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from './a2t-shared.module';
import * as i2 from '@angular/common';
import * as i3 from '@angular/forms';
import * as i4 from '@angular/router';
export const A2tSharedModuleNgFactory:i0.NgModuleFactory<i1.A2tSharedModule> = i0.ɵcmf(i1.A2tSharedModule,
    ([] as any[]),(_l:any) => {
      return i0.ɵmod([i0.ɵmpd(512,i0.ComponentFactoryResolver,i0.ɵCodegenComponentFactoryResolver,
          [[8,([] as any[])],[3,i0.ComponentFactoryResolver],i0.NgModuleRef]),i0.ɵmpd(4608,
          i2.NgLocalization,i2.NgLocaleLocalization,[i0.LOCALE_ID]),i0.ɵmpd(4608,i3.FormBuilder,
          i3.FormBuilder,([] as any[])),i0.ɵmpd(4608,i3.ɵi,i3.ɵi,([] as any[])),i0.ɵmpd(512,
          i2.CommonModule,i2.CommonModule,([] as any[])),i0.ɵmpd(512,i3.ɵba,i3.ɵba,
          ([] as any[])),i0.ɵmpd(512,i3.ReactiveFormsModule,i3.ReactiveFormsModule,
          ([] as any[])),i0.ɵmpd(512,i4.RouterModule,i4.RouterModule,[[2,i4.ɵa],[2,
          i4.Router]]),i0.ɵmpd(512,i1.A2tSharedModule,i1.A2tSharedModule,([] as any[]))]);
    });
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL2hvbWUvamFzb24vYW5ndWxhcjItdG9rZW4vc3JjL2EydC11aS9hMnQtc2hhcmVkL2EydC1zaGFyZWQubW9kdWxlLm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL2hvbWUvamFzb24vYW5ndWxhcjItdG9rZW4vc3JjL2EydC11aS9hMnQtc2hhcmVkL2EydC1zaGFyZWQubW9kdWxlLnRzIl0sInNvdXJjZXNDb250ZW50IjpbIiAiXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OzsifQ==
