/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from '@angular/common';
import * as i2 from './a2t-error.component';
const styles_A2tErrorComponent:any[] = ['div[_ngcontent-%COMP%] {\n            width: 100%;\n            background-color: #df6564;\n            color: white;\n            font-weight: 300;\n            font-size: 15px;\n            padding: 10px 20px;\n            border-radius: 3px;\n            margin-bottom: 15px;\n        }\n\n        div[_ngcontent-%COMP%]    > p[_ngcontent-%COMP%] {\n            margin-bottom: 0;\n        }'];
export const RenderType_A2tErrorComponent:i0.RendererType2 = i0.ɵcrt({encapsulation:0,
    styles:styles_A2tErrorComponent,data:{}});
function View_A2tErrorComponent_1(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,(null as any),(null as any),2,'div',([] as any[]),
      (null as any),(null as any),(null as any),(null as any),(null as any))),(_l()(),
      i0.ɵeld(0,(null as any),(null as any),1,'p',([] as any[]),(null as any),(null as any),
          (null as any),(null as any),(null as any))),(_l()(),i0.ɵted((null as any),
      ['','']))],(null as any),(_ck,_v) => {
    const currVal_0:any = _v.context.$implicit;
    _ck(_v,2,0,currVal_0);
  });
}
export function View_A2tErrorComponent_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵand(16777216,(null as any),(null as any),1,(null as any),
      View_A2tErrorComponent_1)),i0.ɵdid(802816,(null as any),0,i1.NgForOf,[i0.ViewContainerRef,
      i0.TemplateRef,i0.IterableDiffers],{ngForOf:[0,'ngForOf']},(null as any))],(_ck,
      _v) => {
    var _co:i2.A2tErrorComponent = _v.component;
    const currVal_0:any = _co.errors;
    _ck(_v,1,0,currVal_0);
  },(null as any));
}
export function View_A2tErrorComponent_Host_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,(null as any),(null as any),1,'a2t-error',([] as any[]),
      (null as any),(null as any),(null as any),View_A2tErrorComponent_0,RenderType_A2tErrorComponent)),
      i0.ɵdid(49152,(null as any),0,i2.A2tErrorComponent,([] as any[]),(null as any),
          (null as any))],(null as any),(null as any));
}
export const A2tErrorComponentNgFactory:i0.ComponentFactory<i2.A2tErrorComponent> = i0.ɵccf('a2t-error',
    i2.A2tErrorComponent,View_A2tErrorComponent_Host_0,{errors:'errors'},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL2hvbWUvamFzb24vYW5ndWxhcjItdG9rZW4vc3JjL2EydC11aS9hMnQtc2hhcmVkL2EydC1lcnJvci9hMnQtZXJyb3IuY29tcG9uZW50Lm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL2hvbWUvamFzb24vYW5ndWxhcjItdG9rZW4vc3JjL2EydC11aS9hMnQtc2hhcmVkL2EydC1lcnJvci9hMnQtZXJyb3IuY29tcG9uZW50LnRzIiwibmc6Ly8vaG9tZS9qYXNvbi9hbmd1bGFyMi10b2tlbi9zcmMvYTJ0LXVpL2EydC1zaGFyZWQvYTJ0LWVycm9yL2EydC1lcnJvci5jb21wb25lbnQudHMuQTJ0RXJyb3JDb21wb25lbnQuaHRtbCIsIm5nOi8vL2hvbWUvamFzb24vYW5ndWxhcjItdG9rZW4vc3JjL2EydC11aS9hMnQtc2hhcmVkL2EydC1lcnJvci9hMnQtZXJyb3IuY29tcG9uZW50LnRzLkEydEVycm9yQ29tcG9uZW50X0hvc3QuaHRtbCJdLCJzb3VyY2VzQ29udGVudCI6WyIgIiwiPGRpdiAqbmdGb3I9XCJsZXQgZXJyb3Igb2YgZXJyb3JzXCI+PHA+e3tlcnJvcn19PC9wPjwvZGl2PiIsIjxhMnQtZXJyb3I+PC9hMnQtZXJyb3I+Il0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7O29CQ0FBO01BQUEsd0VBQWtDO2FBQUE7VUFBQSw0Q0FBRztNQUFBO0lBQUE7SUFBQTs7OztvQkFBckM7TUFBQSxrQ0FBQTt1Q0FBQTs7O0lBQUs7SUFBTCxXQUFLLFNBQUw7Ozs7b0JDQUE7TUFBQTthQUFBO1VBQUE7OzsifQ==
