/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from './a2t-headline.component';
const styles_A2tHeadlineComponent:any[] = ['p[_ngcontent-%COMP%] {\n            text-align: center;\n            color: white;\n            font-size: 30px;\n        }'];
export const RenderType_A2tHeadlineComponent:i0.RendererType2 = i0.ɵcrt({encapsulation:0,
    styles:styles_A2tHeadlineComponent,data:{}});
export function View_A2tHeadlineComponent_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,(null as any),(null as any),1,'p',([] as any[]),
      (null as any),(null as any),(null as any),(null as any),(null as any))),i0.ɵncd((null as any),
      0)],(null as any),(null as any));
}
export function View_A2tHeadlineComponent_Host_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,(null as any),(null as any),1,'a2t-headline',
      ([] as any[]),(null as any),(null as any),(null as any),View_A2tHeadlineComponent_0,
      RenderType_A2tHeadlineComponent)),i0.ɵdid(49152,(null as any),0,i1.A2tHeadlineComponent,
      ([] as any[]),(null as any),(null as any))],(null as any),(null as any));
}
export const A2tHeadlineComponentNgFactory:i0.ComponentFactory<i1.A2tHeadlineComponent> = i0.ɵccf('a2t-headline',
    i1.A2tHeadlineComponent,View_A2tHeadlineComponent_Host_0,{},{},['*']);
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL2hvbWUvamFzb24vYW5ndWxhcjItdG9rZW4vc3JjL2EydC11aS9hMnQtc2hhcmVkL2EydC1oZWFkbGluZS9hMnQtaGVhZGxpbmUuY29tcG9uZW50Lm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL2hvbWUvamFzb24vYW5ndWxhcjItdG9rZW4vc3JjL2EydC11aS9hMnQtc2hhcmVkL2EydC1oZWFkbGluZS9hMnQtaGVhZGxpbmUuY29tcG9uZW50LnRzIiwibmc6Ly8vaG9tZS9qYXNvbi9hbmd1bGFyMi10b2tlbi9zcmMvYTJ0LXVpL2EydC1zaGFyZWQvYTJ0LWhlYWRsaW5lL2EydC1oZWFkbGluZS5jb21wb25lbnQudHMuQTJ0SGVhZGxpbmVDb21wb25lbnQuaHRtbCIsIm5nOi8vL2hvbWUvamFzb24vYW5ndWxhcjItdG9rZW4vc3JjL2EydC11aS9hMnQtc2hhcmVkL2EydC1oZWFkbGluZS9hMnQtaGVhZGxpbmUuY29tcG9uZW50LnRzLkEydEhlYWRsaW5lQ29tcG9uZW50X0hvc3QuaHRtbCJdLCJzb3VyY2VzQ29udGVudCI6WyIgIiwiPHA+PG5nLWNvbnRlbnQ+PC9uZy1jb250ZW50PjwvcD4iLCI8YTJ0LWhlYWRsaW5lPjwvYTJ0LWhlYWRsaW5lPiJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7O29CQ0FBO01BQUEsK0VBQUc7TUFBQTs7O29CQ0FIO01BQUE7cUNBQUEsVUFBQTtNQUFBOzs7In0=
