/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from './a2t-headline.component';
const styles_A2tHeadlineComponent:any[] = ['p[_ngcontent-%COMP%] {\n            text-align: center;\n            color: white;\n            font-size: 30px;\n        }'];
export const RenderType_A2tHeadlineComponent:i0.RendererType2 = i0.ɵcrt({encapsulation:0,
    styles:styles_A2tHeadlineComponent,data:{}});
export function View_A2tHeadlineComponent_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,(null as any),(null as any),1,'p',([] as any[]),
      (null as any),(null as any),(null as any),(null as any),(null as any))),i0.ɵncd((null as any),
      0)],(null as any),(null as any));
}
export function View_A2tHeadlineComponent_Host_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,(null as any),(null as any),1,'a2t-headline',
      ([] as any[]),(null as any),(null as any),(null as any),View_A2tHeadlineComponent_0,
      RenderType_A2tHeadlineComponent)),i0.ɵdid(49152,(null as any),0,i1.A2tHeadlineComponent,
      ([] as any[]),(null as any),(null as any))],(null as any),(null as any));
}
export const A2tHeadlineComponentNgFactory:i0.ComponentFactory<i1.A2tHeadlineComponent> = i0.ɵccf('a2t-headline',
    i1.A2tHeadlineComponent,View_A2tHeadlineComponent_Host_0,{},{},['*']);
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL2hvbWUvY29yd2luL3Byb2plY3RzL2FuZ3VsYXIyLXRva2VuL3NyYy9hMnQtdWkvYTJ0LXNoYXJlZC9hMnQtaGVhZGxpbmUvYTJ0LWhlYWRsaW5lLmNvbXBvbmVudC5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9ob21lL2Nvcndpbi9wcm9qZWN0cy9hbmd1bGFyMi10b2tlbi9zcmMvYTJ0LXVpL2EydC1zaGFyZWQvYTJ0LWhlYWRsaW5lL2EydC1oZWFkbGluZS5jb21wb25lbnQudHMiLCJuZzovLy9ob21lL2Nvcndpbi9wcm9qZWN0cy9hbmd1bGFyMi10b2tlbi9zcmMvYTJ0LXVpL2EydC1zaGFyZWQvYTJ0LWhlYWRsaW5lL2EydC1oZWFkbGluZS5jb21wb25lbnQudHMuQTJ0SGVhZGxpbmVDb21wb25lbnQuaHRtbCIsIm5nOi8vL2hvbWUvY29yd2luL3Byb2plY3RzL2FuZ3VsYXIyLXRva2VuL3NyYy9hMnQtdWkvYTJ0LXNoYXJlZC9hMnQtaGVhZGxpbmUvYTJ0LWhlYWRsaW5lLmNvbXBvbmVudC50cy5BMnRIZWFkbGluZUNvbXBvbmVudF9Ib3N0Lmh0bWwiXSwic291cmNlc0NvbnRlbnQiOlsiICIsIjxwPjxuZy1jb250ZW50PjwvbmctY29udGVudD48L3A+IiwiPGEydC1oZWFkbGluZT48L2EydC1oZWFkbGluZT4iXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7OztvQkNBQTtNQUFBLCtFQUFHO01BQUE7OztvQkNBSDtNQUFBO3FDQUFBLFVBQUE7TUFBQTs7OyJ9
