/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from '../a2t-shared/a2t-headline/a2t-headline.component.ngfactory';
import * as i2 from '../a2t-shared/a2t-headline/a2t-headline.component';
import * as i3 from '../a2t-shared/a2t-error/a2t-error.component.ngfactory';
import * as i4 from '../a2t-shared/a2t-error/a2t-error.component';
import * as i5 from '../a2t-shared/a2t-form/a2t-form.component.ngfactory';
import * as i6 from '../a2t-shared/a2t-form/a2t-form.component';
import * as i7 from '../a2t-shared/a2t-form/a2t-form.service';
import * as i8 from './a2t-update-password.component';
import * as i9 from '../../angular2-token.service';
import * as i10 from '@angular/router';
const styles_A2tUpdatePasswordComponent:any[] = ([] as any[]);
export const RenderType_A2tUpdatePasswordComponent:i0.RendererType2 = i0.ɵcrt({encapsulation:2,
    styles:styles_A2tUpdatePasswordComponent,data:{}});
export function View_A2tUpdatePasswordComponent_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵted((null as any),['\n        '])),(_l()(),i0.ɵeld(0,
      (null as any),(null as any),2,'a2t-headline',([] as any[]),(null as any),(null as any),
      (null as any),i1.View_A2tHeadlineComponent_0,i1.RenderType_A2tHeadlineComponent)),
      i0.ɵdid(49152,(null as any),0,i2.A2tHeadlineComponent,([] as any[]),(null as any),
          (null as any)),(_l()(),i0.ɵted(0,['Update your Password'])),(_l()(),i0.ɵted((null as any),
          ['\n        '])),(_l()(),i0.ɵeld(0,(null as any),(null as any),1,'a2t-error',
          ([] as any[]),(null as any),(null as any),(null as any),i3.View_A2tErrorComponent_0,
          i3.RenderType_A2tErrorComponent)),i0.ɵdid(49152,(null as any),0,i4.A2tErrorComponent,
          ([] as any[]),{errors:[0,'errors']},(null as any)),(_l()(),i0.ɵted((null as any),
          ['\n        '])),(_l()(),i0.ɵeld(0,(null as any),(null as any),2,'a2t-form',
          ([] as any[]),(null as any),(null as any),(null as any),i5.View_A2tFormComponent_0,
          i5.RenderType_A2tFormComponent)),i0.ɵdid(49152,(null as any),0,i6.A2tFormComponent,
          [i7.A2tFormService],(null as any),(null as any)),(_l()(),i0.ɵted(0,['Update Password'])),
      (_l()(),i0.ɵted((null as any),['\n    ']))],(_ck,_v) => {
    var _co:i8.A2tUpdatePasswordComponent = _v.component;
    const currVal_0:any = _co._errors;
    _ck(_v,6,0,currVal_0);
  },(null as any));
}
export function View_A2tUpdatePasswordComponent_Host_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,(null as any),(null as any),2,'a2t-update-password',
      ([] as any[]),(null as any),(null as any),(null as any),View_A2tUpdatePasswordComponent_0,
      RenderType_A2tUpdatePasswordComponent)),i0.ɵprd(512,(null as any),i7.A2tFormService,
      i7.A2tFormService,([] as any[])),i0.ɵdid(49152,(null as any),0,i8.A2tUpdatePasswordComponent,
      [i7.A2tFormService,i9.Angular2TokenService,i10.Router],(null as any),(null as any))],
      (null as any),(null as any));
}
export const A2tUpdatePasswordComponentNgFactory:i0.ComponentFactory<i8.A2tUpdatePasswordComponent> = i0.ɵccf('a2t-update-password',
    i8.A2tUpdatePasswordComponent,View_A2tUpdatePasswordComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL2hvbWUvamFzb24vYW5ndWxhcjItdG9rZW4vc3JjL2EydC11aS9hMnQtdXBkYXRlLXBhc3N3b3JkL2EydC11cGRhdGUtcGFzc3dvcmQuY29tcG9uZW50Lm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL2hvbWUvamFzb24vYW5ndWxhcjItdG9rZW4vc3JjL2EydC11aS9hMnQtdXBkYXRlLXBhc3N3b3JkL2EydC11cGRhdGUtcGFzc3dvcmQuY29tcG9uZW50LnRzIiwibmc6Ly8vaG9tZS9qYXNvbi9hbmd1bGFyMi10b2tlbi9zcmMvYTJ0LXVpL2EydC11cGRhdGUtcGFzc3dvcmQvYTJ0LXVwZGF0ZS1wYXNzd29yZC5jb21wb25lbnQudHMuQTJ0VXBkYXRlUGFzc3dvcmRDb21wb25lbnQuaHRtbCIsIm5nOi8vL2hvbWUvamFzb24vYW5ndWxhcjItdG9rZW4vc3JjL2EydC11aS9hMnQtdXBkYXRlLXBhc3N3b3JkL2EydC11cGRhdGUtcGFzc3dvcmQuY29tcG9uZW50LnRzLkEydFVwZGF0ZVBhc3N3b3JkQ29tcG9uZW50X0hvc3QuaHRtbCJdLCJzb3VyY2VzQ29udGVudCI6WyIgIiwiXG4gICAgICAgIDxhMnQtaGVhZGxpbmU+VXBkYXRlIHlvdXIgUGFzc3dvcmQ8L2EydC1oZWFkbGluZT5cbiAgICAgICAgPGEydC1lcnJvciBbZXJyb3JzXT1cIl9lcnJvcnNcIj48L2EydC1lcnJvcj5cbiAgICAgICAgPGEydC1mb3JtPlVwZGF0ZSBQYXNzd29yZDwvYTJ0LWZvcm0+XG4gICAgIiwiPGEydC11cGRhdGUtcGFzc3dvcmQ+PC9hMnQtdXBkYXRlLXBhc3N3b3JkPiJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7O29CQ0FBLCtDQUNRO01BQUE7TUFBQTthQUFBO1VBQUEsZUFBYyw2Q0FBbUM7VUFBQSxpQkFDakQ7VUFBQTt5Q0FBQSxVQUFBO1VBQUEsbURBQTBDO1VBQUEsaUJBQzFDO1VBQUE7d0NBQUEsVUFBQTtVQUFBLGlEQUFVO01BQTBCOztJQUR6QjtJQUFYLFdBQVcsU0FBWDs7OztvQkNGUjtNQUFBOzJDQUFBO3dCQUFBLHNCQUFBO01BQUE7Ozs7In0=
